apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: rbcs-svc
    rbcs-app: dev
  name: balance-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: rbcs-svc
      rbcs-app: dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 10
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600
  template:
      metadata:
        labels:
          k8s-app: rbcs-svc
          rbcs-app: dev
        name: balance-app
        namespace: dev
      spec:
        nodeSelector:
          rbcs-app: dev
        containers:
        - name: balance-app
          image: ${image}
          imagePullPolicy: Always
          env:
            - name: LANG
              value: en_US.UTF-8
            - name: LC_ALL
              value: en_US.UTF-8
            - name: JAVA_OPTS
              value: -Xms4g -Xmx8g -Xmn1G -XX:+UseConcMarkSweepGC -XX:+UseAdaptiveSizePolicy -XX:+PrintGCDetails
          args: ["/bin/sh", "-c", "set -e && java -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Dspring.profiles.active=dev -jar rbcs-balance-app-biz-20250222.jar"]
          ports:
            - containerPort: 8031
              name: web
              protocol: TCP
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - 'curl -X GET  ''http://localhost:8031/rbcs/{SVC}/actuator/deregister'';\'
                  - sleep 10;
          readinessProbe:
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
            tcpSocket:
              port: 8031
        terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: balance-app
  namespace: dev
  labels:
    k8s-app: rbcs-svc
    rbcs-app: dev
spec:
  selector:
    k8s-app: rbcs-svc
    rbcs-app: dev
  ports:
    - name: web
      protocol: TCP
      port: 8031
      targetPort: 8031